name: Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go/go.mod'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Generate ANTLR Parser
      run: java -jar scripts/antlr.jar -Dlanguage=Go -visitor -package parser -o go/parser Requirements.g4

    - name: Build
      working-directory: ./go
      run: go build -v ./...

    - name: Test
      working-directory: ./go
      run: go test -v ./...
